### ISSUE TITLE
Can a client call a server-side function?

### ISSUE THREAD

**Issue by Jane-Zheng** [adap/flower#3118] opened 2024-03-12 13:55 UTC
### What is your question?

The sample program demonstrates a server-side call to a client-side function. Can a client call a server-side function?

**Comment by WilliamLindskog** [comment] 2024-12-04 23:11
Hi @Jane-Zheng

Thanks for posting your question here. Could you give more details to which example you are referring to?

**Comment by WilliamLindskog** [comment] 2024-12-09 21:03
By design, Flower supports server-to-client communication, where the server orchestrates tasks and clients report results. Direct client-to-server function calls are not natively supported as this would require significant architectural changes.

In the [Flower tutorial on customizing the client](https://flower.ai/docs/framework/tutorial-series-customize-the-client-pytorch.html), the focus is on tailoring client behavior within Flower. You can also find more information [here](https://flower.ai/docs/framework/how-to-implement-strategies.html) about how Flower communicates information. 

Closing this issue for now.

**Closed by WilliamLindskog** 2024-12-09 21:03 UTC
Labels: question
