### ISSUE TITLE
android apk cannot be installed on android smartphone

### ISSUE THREAD

**Issue by SHAO-Jiaqi757** [adap/flower#1019] opened 2022-01-21 11:11 UTC
### Describe what the documentation is missing.

I have tried to install the demo android app on the Xiaomi/Huawei smartphone, but it is failed for inadaptation with the OS.

**Comment by sisco0** [comment] 2022-01-30 07:36
In the `examples/android/client/app/build.gradle` file you could find the build configuration for the current package. The `targetSdkVersion` and `compileSdkVersion` is set to 29, which refers to _Android 10.0_. Also, check out this issue https://github.com/adap/flower/issues/930 where I suggest adding different platforms as targets:

```json
        include 'x86', 'armeabi-v7a', 'x86_64'
```

All the information you need for solving the issue is querying your device about its _Android_ version and its CPU platform, where this second point could be checked out by running `adb shell getprop ro.product.cpu.abilist`. Kindly checkout also the APKs shared in the following linked _Google Drive_ link if you do not want to compile by yourself and want to run a quick platform test after ensuring your _Android_ version is greater or equal than 10:

https://drive.google.com/drive/folders/1kpygk5YIagLTWWjGXJ6PjHYPj3_KSNE9?usp=sharing

**Comment by WilliamLindskog** [comment] 2024-12-05 15:57
Hi @SHAO-Jiaqi757 

Thanks for raising this. Are you still experiencing this issue? If so, could you provide more details on your implementation?

**Comment by WilliamLindskog** [comment] 2024-12-06 14:16
Closing this issue for now.

**Closed by WilliamLindskog** 2024-12-06 14:16 UTC
Labels: documentation
