### ISSUE TITLE
Add Flower Baseline: FedDebug

### ISSUE THREAD

**Issue by warisgill** [adap/flower#3051] opened 2024-03-04 03:45 UTC
### Paper

Waris Gill, Ali Anwar, Muhammad Ali Gulzar (2023). FedDebug: Systematic Debugging for Federated Learning Applications

### Link

https://dl.acm.org/doi/pdf/10.1109/ICSE48619.2023.00053

### Maybe give motivations about why the paper should be implemented as a baseline.

FedDebug introduces the first testing and debugging technique for Federated Learning (FL) applications. It addresses the challenge of identifying faulty client models during the aggregation process on the server, which lacks test data. This paper proposes differential testing for FL, which localizes a faulty client by comparing neuron activations, eliminating the need for real-world test data. FedDebug's uniqueness lies in its compatibility with any variant of FedAvg, as it integrates seamlessly without necessitating changes to existing aggregation protocols. For more detail, please read [FedDebug paper](https://chalianwar.github.io/files/feddebug.pdf). 

![image](https://github.com/adap/flower/assets/44170206/53ff8152-6f3e-4fcc-b4c0-85526be0543b)

### Is there something else you want to add?

FedDebug was presented at ICSE-2023, a prestigious conference in software engineering. Dr. Nicholas Lane mentioned our paper in a tweet, suggesting its port to Flwr. https://twitter.com/niclane7/status/1622865906874388484 

We also published [FedDefender](https://arxiv.org/abs/2307.08672), a tool for detecting backdoor attacks in Federated Learning. It's already implemented in Flwr ([Github Link](https://github.com/warisgill/FedDefender/tree/main/project)), and I plan to open an issue to include FedDefender as a baseline as well. The advantage of these papers is that they don't necessitate any changes in aggregation techniques and can work with any existing fusion methods.

### For first time contributors

- [x]  Read the [`first contribution` doc](https://flower.ai/docs/first-time-contributors.html)
- [x]  Complete the Flower tutorial
- [x]  Read the Flower Baselines docs to get an overview:
    - [x]  [How to use Flower Baselines](https://flower.ai/docs/baselines/how-to-use-baselines.html)
    - [x]  [How to contribute a Flower Baseline](https://flower.ai/docs/baselines/how-to-contribute-baselines.html)

### Prepare - understand the scope

- [x] Read the paper linked above
- [x] Decide which experiments you'd like to reproduce. The more the better!
- [x] Follow the steps outlined in [Add a new Flower Baseline](https://flower.ai/docs/baselines/how-to-contribute-baselines.html#add-a-new-flower-baseline).
- [x] You can use as reference [other baselines](https://github.com/adap/flower/tree/main/baselines) that the community merged following those steps.

### Verify your implementation

- [x] Follow the steps indicated in the `EXTENDED_README.md` that was created in your baseline directory
- [x] Ensure your code reproduces the results for the experiments you chose
- [x] Ensure your `README.md` is ready to be run by someone that is no familiar with your code. Are all step-by-step instructions clear?
- [x] Ensure running the formatting and typing tests for your baseline runs without errors.
- [x] Clone your repo on a new directory, follow the guide on your own `README.md` and verify everything runs.

**Comment by jafermarq** [comment] 2024-03-04 13:25
Hey @warisgill, thanks for opening the issue. Having `FedDebug` would be great! The process to create a baseline is simple, just follow the steps in the [_Contributing a new baseline_](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline) section. Or if you prefer a bit more guidance, you'll find a step-by-step guide in [our documentation](https://flower.ai/docs/baselines/how-to-contribute-baselines.html).

Usually baselines implement at least the "core results" of the paper, since those are often the most useful for people wanting to either reproduce the results in the paper or want to compare them against other baselines. What plot/tables are you thinking of reproducing with your baseline in Flower?

**Comment by warisgill** [comment] 2024-03-05 23:33
Hi @jafermarq , thank you so much. Table 2 and Figure 10 are mainly the core results of the paper. So, I will first implement the FedDebug technique in a generic way so that anyone can use it with any Fusion technique and with any CNN architecture. Then I will reproduce the Table 2 and Figure 10 results. If you have any suggestions, please share it with me. Thanks a lot.

**Comment by jafermarq** [comment] 2024-03-20 20:54
Hi @warisgill what you propose makes sense. Let me know when you'd like me to review your pull request :)

**Comment by warisgill** [comment] 2024-07-12 09:10
Hi @jafermarq , I have created the PR. I have closely followed the guidelines. Please let me know if there is anything I need to fix. Thank you so much.

**Comment by gautamjajoo** [comment] 2024-11-18 19:46
Hey @warisgill! Can I give a shot at [FedDefender](https://arxiv.org/abs/2307.08672)? If you are not working on it

**Comment by warisgill** [comment] 2024-11-18 23:09
@gautamjajoo  Hi, sure! Definitely, you can work on it. If you start with the FedDebug Flower baseline, 80 percent of the work is already completed.

**Comment by jafermarq** [comment] 2024-11-19 01:46
Great to see this interaction!! 🙌 @warisgill @gautamjajoo. 

Now that `FedDebug` is completed, I'm closing this issue (I forgot doing it a few weeks back when the `FedDebug` baseline was merged). Feel free to continue the chat here, or [on Slack](https://flower.ai/join-slack/) or on [Flower Discuss](https://discuss.flower.ai/) 🚀

**Closed by jafermarq** 2024-11-19 01:46 UTC
Labels: good first issue, new baseline
