### ISSUE TITLE
Flower for training of different models

### ISSUE THREAD

**Issue by sauravtii** [adap/flower#1748] opened 2023-03-27 10:42 UTC
### What is your question?

Can we use flower to train a ML model (mostly a transformer) with different initial conditions?
For example: 1 client might have a model that was trained for 5 epochs, the next client has a model that was trained for 15 epochs, and so on and we want to train these models in a federated manner using flower.

**Comment by adam-narozniak** [comment] 2023-03-28 16:53
For anyone interested the duplicate of this question was answered here: https://friendly-flower.slack.com/archives/C01RM6LMKQA/p1679911889455429

**Comment by tanertopal** [comment] 2023-04-18 14:18
I am closing this as it's answered in Slack. @sauravtii feel free to re-open it.

**Closed by tanertopal** 2023-04-18 14:18 UTC
Labels: question
