### ISSUE TITLE
 When the system language is set to Chinese, using the "flwr new" command results in a {'gbk' codec can't encode character '\u2b50'} error.

### ISSUE THREAD

**Issue by TNTcontroller** [adap/flower#4657] opened 2024-12-09 07:22 UTC
### Describe the bug

When the system language is set to Chinese, using the "flwr new" command results in a 'gbk' codec can't encode character '\u2b50' error.'\u2b50' is⭐, which is write in flwr/cli/new/templates/app/Readme.md.tpl，

 I have found an effective solution. Change:
“file_path.write_text(content)”  in the create_file() function in flwr/cli/new/new.py, to
`
file_path.write_text(content, encoding="utf-8")
`

 However, I am not sure if this will cause other bugs on computers in other languages.

### Steps/Code to Reproduce

system language: Chinese
flwr new
app name: no matter what.
username: no matter what.
framework: 0 which is Pytorch.

### Expected Results

💬 Please select ML framework by typing in the number

 [ 0] PyTorch
 [ 1] TensorFlow
 [ 2] sklearn
 [ 3] HuggingFace
 [ 4] JAX
 [ 5] MLX
 [ 6] NumPy
 [ 7] FlowerTune
 [ 8] Flower Baseline

: 0

🔨 Creating Flower App pytorchflower...
🎊 Flower App creation successful.

To run your Flower App, use the following command:

        flwr run pytorchflower

If you haven't installed all dependencies yet, follow these steps:

        cd pytorchflower
        pip install -e .
        flwr run .

### Actual Results

🔨 Creating Flower App pytorchflower...
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\ALotOfLibrary\Anaconda\envs\flower_fed\lib\site-packages\flwr\cli\new\new.py:265 in new                           │
│                                                                                                                      │
│   262 │   │   │   files["LICENSE"] = {"template": "app/LICENSE.tpl"}                                                 │
│   263 │                                                                                                              │
│   264 │   for file_path, value in files.items():                                                                     │
│ ❱ 265 │   │   render_and_create(                                                                                     │
│   266 │   │   │   file_path=project_dir / file_path,                                                                 │
│   267 │   │   │   template=value["template"],                                                                        │
│   268 │   │   │   context=context,                                                                                   │
│                                                                                                                      │
│ ╭───────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────╮ │
│ │              app_name = 'pytorchflower'                                                                          │ │
│ │               context = {                                                                                        │ │
│ │                         │   'framework_str': 'PyTorch',                                                          │ │
│ │                         │   'import_name': 'pytorchflower',                                                      │ │
│ │                         │   'package_name': 'pytorchflower',                                                     │ │
│ │                         │   'project_name': 'pytorchflower',                                                     │ │
│ │                         │   'username': 'tnt'                                                                    │ │
│ │                         }                                                                                        │ │
│ │             file_path = 'README.md'                                                                              │ │
│ │                 files = {                                                                                        │ │
│ │                         │   '.gitignore': {'template': 'app/.gitignore.tpl'},                                    │ │
│ │                         │   'README.md': {'template': 'app/README.md.tpl'},                                      │ │
│ │                         │   'pyproject.toml': {'template': 'app/pyproject.pytorch.toml.tpl'},                    │ │
│ │                         │   'pytorchflower/__init__.py': {'template': 'app/code/__init__.py.tpl'},               │ │
│ │                         │   'pytorchflower/server_app.py': {'template': 'app/code/server.pytorch.py.tpl'},       │ │
│ │                         │   'pytorchflower/client_app.py': {'template': 'app/code/client.pytorch.py.tpl'},       │ │
│ │                         │   'pytorchflower/task.py': {'template': 'app/code/task.pytorch.py.tpl'}                │ │
│ │                         }                                                                                        │ │
│ │             framework = None                                                                                     │ │
│ │         framework_str = 'PyTorch'                                                                                │ │
│ │ frameworks_with_tasks = ['PyTorch', 'JAX', 'HuggingFace', 'MLX', 'TensorFlow', 'sklearn', 'NumPy']               │ │
│ │           import_name = 'pytorchflower'                                                                          │ │
│ │     llm_challenge_str = None                                                                                     │ │
│ │          package_name = 'pytorchflower'                                                                          │ │
│ │           project_dir = WindowsPath('D:/programmingProject/python/__deepLearning_related/__federated_learning_r… │ │
│ │         template_name = 'pytorch'                                                                                │ │
│ │              username = 'tnt'                                                                                    │ │
│ │                 value = {'template': 'app/README.md.tpl'}                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                      │
│ D:\ALotOfLibrary\Anaconda\envs\flower_fed\lib\site-packages\flwr\cli\new\new.py:90 in render_and_create              │
│                                                                                                                      │
│    87 def render_and_create(file_path: Path, template: str, context: dict[str, str]) -> None:                        │
│    88 │   """Render template and write to file."""                                                                   │
│    89 │   content = render_template(template, context)                                                               │
│ ❱  90 │   create_file(file_path, content)                                                                            │
│    91                                                                                                                │
│    92                                                                                                                │
│    93 # pylint: disable=too-many-locals,too-many-branches,too-many-statements                                        │
│                                                                                                                      │
│ ╭───────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────╮ │
│ │   content = '# pytorchflower: A Flower / PyTorch app\n\n## Install dependencies and project\n\n``'+858           │ │
│ │   context = {                                                                                                    │ │
│ │             │   'framework_str': 'PyTorch',                                                                      │ │
│ │             │   'import_name': 'pytorchflower',                                                                  │ │
│ │             │   'package_name': 'pytorchflower',                                                                 │ │
│ │             │   'project_name': 'pytorchflower',                                                                 │ │
│ │             │   'username': 'tnt'                                                                                │ │
│ │             }                                                                                                    │ │
│ │ file_path = WindowsPath('D:/programmingProject/python/__deepLearning_related/__federated_learning_related/flowe… │ │
│ │  template = 'app/README.md.tpl'                                                                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                      │
│ D:\ALotOfLibrary\Anaconda\envs\flower_fed\lib\site-packages\flwr\cli\new\new.py:84 in create_file                    │
│                                                                                                                      │
│    81 def create_file(file_path: Path, content: str) -> None:                                                        │
│    82 │   """Create file including all nessecary directories and write content into file."""                         │
│    83 │   file_path.parent.mkdir(exist_ok=True)                                                                      │
│ ❱  84 │   file_path.write_text(content)                                                                              │
│    85                                                                                                                │
│    86                                                                                                                │
│    87 def render_and_create(file_path: Path, template: str, context: dict[str, str]) -> None:                        │
│                                                                                                                      │
│ ╭───────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────╮ │
│ │   content = '# pytorchflower: A Flower / PyTorch app\n\n## Install dependencies and project\n\n``'+858           │ │
│ │ file_path = WindowsPath('D:/programmingProject/python/__deepLearning_related/__federated_learning_related/flowe… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                      │
│ D:\ALotOfLibrary\Anaconda\envs\flower_fed\lib\pathlib.py:1155 in write_text                                          │
│                                                                                                                      │
│   1152 │   │   │   │   │   │   │   data.__class__.__name__)                                                          │
│   1153 │   │   encoding = io.text_encoding(encoding)                                                                 │
│   1154 │   │   with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f                      │
│ ❱ 1155 │   │   │   return f.write(data)                                                                              │
│   1156 │                                                                                                             │
│   1157 │   def readlink(self):                                                                                       │
│   1158 │   │   """                                                                                                   │
│                                                                                                                      │
│ ╭───────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────╮ │
│ │     data = '# pytorchflower: A Flower / PyTorch app\n\n## Install dependencies and project\n\n``'+858            │ │
│ │ encoding = 'locale'                                                                                              │ │
│ │   errors = None                                                                                                  │ │
│ │        f = <_io.TextIOWrapper                                                                                    │ │
│ │            name='D:\\programmingProject\\python\\__deepLearning_related\\__federated_learning_related\\flower_f… │ │
│ │            mode='w' encoding='cp936'>                                                                            │ │
│ │  newline = None                                                                                                  │ │
│ │     self = WindowsPath('D:/programmingProject/python/__deepLearning_related/__federated_learning_related/flower… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
UnicodeEncodeError: 'gbk' codec can't encode character '\u2b50' in position 782: illegal multibyte sequence

**Comment by WilliamLindskog** [comment] 2024-12-10 17:58
Hi 

thank you for raising this. @jafermarq do we need to change the characters used?

**Comment by jafermarq** [comment] 2024-12-10 18:03
Hi @TNTcontroller, thanks for opening the issue. We recently opened a PR (https://github.com/adap/flower/pull/4653) that introduces the same fix as you propose. However, i think the issue is related to Windows and not necessarily to the usage of Chinese characters. 

Did you encounter other commands not working as expected?

**Comment by jafermarq** [comment] 2024-12-12 15:48
Hi @TNTcontroller , we just merged the PR I mentioned above. The next release of flower will come with the fix. Please reach out if you experience other issues in Windows. From my experience, flower runs best in WSL

**Closed by jafermarq** 2024-12-12 15:48 UTC
Labels: type: bug, state: revision needed, part: misc framework

**Comment by TNTcontroller** [comment] 2024-12-13 16:45
I have not encountered other not working commands. Thank you for resolving my issue.
