### ISSUE TITLE
Add FedNova baseline

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#943] opened 2021-12-14 15:31 UTC
FedNova paper: https://arxiv.org/pdf/2007.07481.pdf

**Comment by sisco0** [comment] 2021-12-20 02:04
Is a new `fednova.py` file expected to be created with its corresponding `fednova_test.py` test file under `src/py/flwr/server/strategy` for solving this issue?

**Comment by danieljanes** [comment] 2022-10-17 21:20
Flower Baselines are a separate from the built-in strategies, here's how to contribute: https://flower.dev/docs/contributing-baselines.html

**Comment by jafermarq** [comment] 2023-12-20 20:09
Closing this since `FedNova` has been implemented as part of _Summer of Reproducibility_: https://github.com/adap/flower/tree/main/baselines/fednova

**Closed by jafermarq** 2023-12-20 20:09 UTC
Labels: enhancement, good first issue, help wanted, new baseline
