### ISSUE TITLE
FL Checkpoint generation

### ISSUE THREAD

**Issue by jafermarq** [adap/flower#599] opened 2021-01-19 10:23 UTC
It would be great to have a checkpointing mechanism built-in in the Flower server. This would serve a dual purpose: keep backups of the last N rounds (global model parameters, round number, strategy status, etc); and, make it easy to replicate the experiment and run the final evaluation of the global model at a later stage. 

I think as a starting point the following elements should go in the checkpoint:

- Model parameters.
- Current round number (so `server.fit()` starts from the round number stored in the checkpoint).
- Strategy-specific parameters. Some strategies might keep track of certain parameters during the training process (?) but others don't (e.g. FedAvg). 
- Anything else that changes over time.

By means of an additional flag (e.g. `--checkpoint <path_to_checkpoint>`) when launching the server, we can indicate that we are in fact resuming an experiment. 

To make the implementation of this functionality easier, it might be a good time to replace the use of `_get_initial_weights()` from the first client that connects to the server and, instead, use the model that lives in the server to initialise all the clients. This will make things easier when loading the model weights from a checkpoint.

**Comment by pedropgusmao** [comment] 2021-01-19 10:47
This should include handling SIGINT.

**Comment by jafermarq** [comment] 2021-01-19 10:57
Checkpoint handling would likely be framework-specific so maybe a good way to add this functionality is by adding a new server argument (e.g. `on_init`) that can be passed when creating the server object. This could be just a user-define function that gets executed right at the end of the server object constructor.

**Comment by tanertopal** [comment] 2021-11-15 10:35
@pedropgusmao @jafermarq @danieljanes is this kind of resolve with this: https://flower.dev/docs/saving-progress.html ?

**Comment by danieljanes** [comment] 2021-11-15 10:38
@tanertopal it's possible with the approach described in the docs, but my understanding is that the issue is about providing a built-in way to save checkpoints automatically

**Comment by WilliamLindskog** [comment] 2024-12-03 20:53
Seeing this is available https://flower.ai/docs/framework/how-to-save-and-load-model-checkpoints.html
Closing this.

**Closed by WilliamLindskog** 2024-12-03 20:53 UTC
