### ISSUE TITLE
Compatibility of Flower with ONNX Runtime

### ISSUE THREAD

**Issue by martinkorelic** [adap/flower#4081] opened 2024-08-25 12:26 UTC
### What is your question?

Hello everyone, I am fairly new to federated learning and flower framework but have been recently researching on device learning.

I have noticed in past forums that there were questions regarding ONNX runtime supporting on device learning (which it does now) - https://github.com/microsoft/onnxruntime/issues/11098.
So my question is, whether Flower framework also offers support for ONNX runtime framework now or is there a plan for it in the future?
If not, is there a workaround that could make ONNX runtime compatible with Flower framework for federated learning?

**Comment by WilliamLindskog** [comment] 2024-12-10 15:43
Hi 

Thanks for raising this issue. This is a duplicate of #3547 so I will close this one. We can continue the discussion in the other raised issue. 

We are always eager to provide the community with features and support for new tech, thus if you are passionate about running ONNX Runtime with Flower, feel free to open a pull request and we will support you throughout the process. Otherwise, we will review this internally and see what it can be implemented. 

Best regards

**Closed by WilliamLindskog** 2024-12-10 15:43 UTC
Labels: question
